export const companiesData = [
  {
    id: "1",
    logo: "./assets/react.svg",
    name: "TechCorp",
    details:
      "TechCorp is a leading technology company specializing in software development and IT solutions.",
    domain: "Backend Development",
    requiredSkills: ["Java", "Spring Boot", "SQL", "RESTful APIs"],
    hiringType: "On Campus",
    workForm: "Full-time",
    placementDate: "2024-03-15",
    minCGPA: 7.5,
    eligibleBranches: [
      "Computer Science",
      "Information Technology",
      "Electronics and Communication",
    ],
  },
  {
    id: "2",
    logo: "./assets/react.svg",
    name: "DataAnalytica",
    details:
      "DataAnalytica focuses on data analysis and provides cutting-edge solutions for data-driven decision-making.",
    domain: "Data Analyst",
    requiredSkills: ["Python", "R", "SQL", "Statistical Analysis"],
    hiringType: "Off Campus",
    workForm: "Internship",
    placementDate: "2024-03-20",
    ctcRange: "5-7 LPA",
  },
  {
    id: "3",
    logo: "./assets/react.svg",
    name: "WebSolutions Inc.",
    details:
      "WebSolutions Inc. is a web development company creating modern and user-friendly web applications.",
    domain: "Frontend Development",
    requiredSkills: ["HTML", "CSS", "JavaScript", "React"],
    hiringType: "On Campus",
    workForm: "Full-time",
    placementDate: "2024-03-25",
    minCGPA: 7.0,
    eligibleBranches: [
      "Computer Science",
      "Information Technology",
      "Software Engineering",
    ],
  },
  {
    id: "4",
    logo: "./assets/react.svg",
    name: "Cloud Innovations",
    details:
      "Cloud Innovations specializes in cloud computing services and offers innovative solutions for businesses.",
    domain: "Cloud Computing",
    requiredSkills: ["AWS", "Azure", "Google Cloud", "DevOps"],
    hiringType: "Off Campus",
    workForm: "Work from Home",
    placementDate: "2024-04-05",
    ctcRange: "8-10 LPA",
  },
  {
    id: "5",
    logo: "./assets/react.svg",
    name: "AI Solutions Co.",
    details:
      "AI Solutions Co. leverages artificial intelligence technologies to provide intelligent solutions for various industries.",
    domain: "Artificial Intelligence",
    requiredSkills: [
      "Machine Learning",
      "Deep Learning",
      "Python",
      "TensorFlow",
    ],
    hiringType: "On Campus",
    workForm: "Part-time",
    placementDate: "2024-04-10",
    minCGPA: 7.0,
    eligibleBranches: [
      "Computer Science",
      "Information Technology",
      "Electrical Engineering",
    ],
  },
  {
    id: "6",
    logo: "./assets/react.svg",
    name: "TechSolutions Ltd.",
    details:
      "TechSolutions Ltd. provides IT consulting services and software solutions for businesses worldwide.",
    domain: "IT Consulting",
    requiredSkills: [
      "Project Management",
      "Software Development Lifecycle",
      "Business Analysis",
    ],
    hiringType: "Off Campus",
    workForm: "Full-time",
    placementDate: "2024-04-15",
    ctcRange: "7-9 LPA",
  },
  {
    id: "7",
    logo: "./assets/react.svg",
    name: "Innovative Minds Co.",
    details:
      "Innovative Minds Co. is a technology company specializing in innovation and product development.",
    domain: "Product Management",
    requiredSkills: [
      "Product Strategy",
      "Market Research",
      "Agile Development",
    ],
    hiringType: "On Campus",
    workForm: "Internship",
    placementDate: "2024-04-20",
    minCGPA: 7.5,
    eligibleBranches: [
      "Computer Science",
      "Information Technology",
      "Electronics and Communication",
    ],
  },
  {
    id: "8",
    logo: "./assets/react.svg",
    name: "MobileApps Inc.",
    details:
      "MobileApps Inc. specializes in mobile app development, creating innovative apps for iOS and Android platforms.",
    domain: "Mobile Development",
    requiredSkills: ["Swift", "Kotlin", "React Native", "Firebase"],
    hiringType: "Off Campus",
    workForm: "Part-time",
    placementDate: "2024-04-25",
    ctcRange: "4-6 LPA",
  },
  {
    id: "9",
    logo: "./assets/react.svg",
    name: "TechSavvy Solutions",
    details:
      "TechSavvy Solutions offers IT consulting services, helping businesses with digital transformation and technology adoption.",
    domain: "IT Consulting",
    requiredSkills: [
      "Project Management",
      "IT Strategy",
      "Cloud Migration",
      "Enterprise Architecture",
    ],
    hiringType: "On Campus",
    workForm: "Full-time",
    placementDate: "2024-05-01",
    minCGPA: 7.0,
    eligibleBranches: [
      "Computer Science",
      "Information Technology",
      "Software Engineering",
    ],
  },
  {
    id: "10",
    logo: "./assets/react.svg",
    name: "GameGenius Studios",
    details:
      "GameGenius Studios develops immersive and engaging video games for various platforms, delighting gamers worldwide.",
    domain: "Game Development",
    requiredSkills: ["Unity", "C#", "Game Design", "3D Modeling"],
    hiringType: "Off Campus",
    workForm: "Internship",
    placementDate: "2024-05-05",
    ctcRange: "6-8 LPA",
  },
  {
    id: "11",
    logo: "./assets/react.svg",
    name: "FinTech Innovations",
    details:
      "FinTech Innovations provides financial technology solutions, revolutionizing the way people manage finances.",
    domain: "Financial Technology",
    requiredSkills: [
      "Blockchain",
      "Cryptocurrency",
      "Financial Analysis",
      "Payment Gateways",
    ],
    hiringType: "On Campus",
    workForm: "Full-time",
    placementDate: "2024-05-10",
    minCGPA: 7.5,
    eligibleBranches: ["Computer Science", "Information Technology", "Finance"],
  },
  {
    id: "12",
    logo: "./assets/react.svg",
    name: "RoboTech Solutions",
    details:
      "RoboTech Solutions specializes in robotics development, creating autonomous systems for various applications.",
    domain: "Robotics",
    requiredSkills: ["ROS", "Python", "Computer Vision", "Machine Learning"],
    hiringType: "On Campus",
    workForm: "Full-time",
    placementDate: "2024-05-15",
    minCGPA: 7.0,
    eligibleBranches: [
      "Mechanical Engineering",
      "Electrical Engineering",
      "Computer Science",
    ],
  },
  {
    id: "13",
    logo: "./assets/react.svg",
    name: "HealthTech Innovations",
    details:
      "HealthTech Innovations develops healthcare technology solutions, improving patient care and health outcomes.",
    domain: "Healthcare Technology",
    requiredSkills: [
      "Health Informatics",
      "Medical Imaging",
      "Health Data Analysis",
      "Telemedicine",
    ],
    hiringType: "On Campus",
    workForm: "Internship",
    placementDate: "2024-05-20",
    minCGPA: 7.0,
    eligibleBranches: [
      "Biomedical Engineering",
      "Computer Science",
      "Health Sciences",
    ],
  },
  // Add more companies here
];

console.log(companiesData);
